package com.myspace.mortgage_process;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Application")
public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Years of amorization")
	private java.lang.Integer amorizatuib;
	@org.kie.api.definition.type.Label(value = "Applicant")
	private com.myspace.mortgage_process.Applicant applicant;
	@org.kie.api.definition.type.Label(value = "Down Payment")
	private java.lang.Integer downpayment;
	@org.kie.api.definition.type.Label(value = "Error details")
	private com.myspace.mortgage_process.ValidationErrorDO errors;
	@org.kie.api.definition.type.Label(value = "Mortgage Amount")
	private java.lang.Integer mortgageamount;
	@org.kie.api.definition.type.Label(value = "Property")
	private com.myspace.mortgage_process.Property property;

	public Application() {
	}

	public java.lang.Integer getAmorizatuib() {
		return this.amorizatuib;
	}

	public void setAmorizatuib(java.lang.Integer amorizatuib) {
		this.amorizatuib = amorizatuib;
	}

	public com.myspace.mortgage_process.Applicant getApplicant() {
		return this.applicant;
	}

	public void setApplicant(com.myspace.mortgage_process.Applicant applicant) {
		this.applicant = applicant;
	}

	public java.lang.Integer getDownpayment() {
		return this.downpayment;
	}

	public void setDownpayment(java.lang.Integer downpayment) {
		this.downpayment = downpayment;
	}

	public com.myspace.mortgage_process.ValidationErrorDO getErrors() {
		return this.errors;
	}

	public void setErrors(com.myspace.mortgage_process.ValidationErrorDO errors) {
		this.errors = errors;
	}

	public java.lang.Integer getMortgageamount() {
		return this.mortgageamount;
	}

	public void setMortgageamount(java.lang.Integer mortgageamount) {
		this.mortgageamount = mortgageamount;
	}

	public com.myspace.mortgage_process.Property getProperty() {
		return this.property;
	}

	public void setProperty(com.myspace.mortgage_process.Property property) {
		this.property = property;
	}

	public Application(java.lang.Integer amorizatuib,
			com.myspace.mortgage_process.Applicant applicant,
			java.lang.Integer downpayment,
			com.myspace.mortgage_process.ValidationErrorDO errors,
			java.lang.Integer mortgageamount,
			com.myspace.mortgage_process.Property property) {
		this.amorizatuib = amorizatuib;
		this.applicant = applicant;
		this.downpayment = downpayment;
		this.errors = errors;
		this.mortgageamount = mortgageamount;
		this.property = property;
	}

}