package com.myspace.mortgage_process;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ValidationErrorDO")
public class ValidationErrorDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "ValidationErrorDO")
	private java.lang.String validationErrorDO;

	public ValidationErrorDO() {
	}

	public java.lang.String getValidationErrorDO() {
		return this.validationErrorDO;
	}

	public void setValidationErrorDO(java.lang.String validationErrorDO) {
		this.validationErrorDO = validationErrorDO;
	}

	public ValidationErrorDO(java.lang.String validationErrorDO) {
		this.validationErrorDO = validationErrorDO;
	}

}